server.port=8080

# Exercise 1
spring.cloud.gateway.routes[0].id=example_route
spring.cloud.gateway.routes[0].uri=https://example.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**

# Exercise 2
spring.cloud.gateway.routes[1].id=load_balanced_route
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# Exercise 3
resilience4j.circuitbreaker.instances.userCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userCircuitBreaker.failureRateThreshold=50